name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: debug1
        run: echo ${{ secrets.DOCKER_HUB_USERNAME }} | base64
      - name: debug2
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | base64
      - uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
