name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build docker image for test only
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
          load: true
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - name: Semantic Release
        id: semantic_release
        uses: docker://macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
        with:
          entrypoint: /bin/sh
          workdir: /home/runner/work/${{ github.repository }}/${{ github.repository }}
          branches: 'main'
          args: -c "cp /configs/$CONFIG_FILE .releaserc && git config --global --add safe.directory /github/workspace && npx semantic-release --branches $RELEASE_BRANCH"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: production
          GH_URL: https://github.com/${{ github.repository }}.git
          RELEASE_BRANCH: main
          CONFIG_FILE: .releaserc-docker.json
          DEBUG: semantic-release:*
      - name: Get latest release
        id: latest_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: merge back to develop
        uses: devmasx/merge-branch@v1.4.0
        with:
          from_branch: 'main'
          target_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore(release): ${{ fromJson(steps.latest_release.outputs.data).tag_name }} merge main to develop'
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: macstab/semantic-release-maven-gradle-nodejs-python-git-jq:${{ fromJson(steps.latest_release.outputs.data).tag_name }}
#      - name: Build and push docker image
#          uses: docker/build-push-action@v5
#          with:
#            context: .
#            file: ./Dockerfile
#            push: true
#            tags: macstab/semantic-release-maven-gradle-nodejs-python-git-jq:${{ steps.semantic_release.outputs.new_release_version }}
