name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: debug1
        run: ls -lah && pwd
      - name: Semantic Release
        uses: docker://macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
        with:
          entrypoint: /bin/sh
          args: -c "git config --global --add safe.directory /github/workspace && git log -n 10 --oneline | cat && pwd && ls -lah && git log && npx semantic-release --config /configs/.releaserc-nobuild.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          GH_URL: https://github.com/${{ github.repository }}.git
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
