name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        uses: docker://macstab/semantic-release-maven-gradle-nodejs-python-git-jq:latest
        with:
          entrypoint: /bin/sh
          args: -c "npx semantic-release --config /configs/.releaserc-nobuild.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
